/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Tutorial: API stubs (final), at
* https://www.jitblox.com/project/QzhPS4ivI5/tutorial-api-stubs-final
*/

export interface WorkItem {
  /**
  * The unique ID of the work item.
  */
  id?: string;
  /**
  * The title of the work item.
  */
  title?: string;
  /**
  * A short description of the work item.
  */
  summary?: string;
  /**
  * The date at which the work item was created.
  */
  dateCreated?: Date;
}
