/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Tutorial: API stubs (final), at
* https://www.jitblox.com/project/QzhPS4ivI5/tutorial-api-stubs-final
*/

import { CommonModule } from '@angular/common';
import { Component, Input } from '@angular/core';
import { WorkItem } from '../../../model';

/**
* A custom component that displays a collection of work items, such as bugs or user stories.
*/
@Component({
  selector: 'app-work-item-list',
  standalone: true,
  templateUrl: './work-item-list.component.html',
  styleUrls: ['./work-item-list.component.scss'],
  imports: [CommonModule]
})
export class WorkItemListComponent {
  @Input() public workItems: WorkItem[] | null = [];

  constructor() {}
}
