/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Tutorial: API stubs (final), at
* https://www.jitblox.com/project/QzhPS4ivI5/tutorial-api-stubs-final
*/

import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { WorkItem } from '../../model';
import { WorkItemsApiService } from '../../services/work-items-api.service';
import { WorkItemListComponent } from '../Components/WorkItems/work-item-list.component';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss'],
  imports: [WorkItemListComponent, CommonModule]
})
export class DashboardComponent implements OnInit {
  public tasks$!: Observable<WorkItem[] | undefined>;

  public bugs$!: Observable<WorkItem[] | undefined>;

  public userStories$!: Observable<WorkItem[] | undefined>;

  constructor(
    private workItemsApiService: WorkItemsApiService
  ) {}

  public ngOnInit(): void {
    this.userStories$ = this.workItemsApiService.fetchUserStories();

    this.bugs$ = this.workItemsApiService.fetchBugs();

    this.tasks$ = this.workItemsApiService.fetchTasks();
  }
}
