/**
* Generated by JitBlox - rapid interactive prototyping of modern web apps from your browser.
* Upgrade to a Pro plan to remove this header, see https://www.jitblox.com/plans for more.
* 
* Check out this JitBlox project, Tutorial: API stubs (final), at
* https://www.jitblox.com/project/QzhPS4ivI5/tutorial-api-stubs-final
*/

import { WorkItem } from '../model';

export const tasks: WorkItem[] = [
  {
    id: 'vKGmIc',
    title: 'Describe user story for search feature',
    summary: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    dateCreated: new Date('2024-05-21')
  },
  {
    id: 'bIPOZM',
    title: 'Create prototype for the new dashboard',
    summary: 'Mauris eget ultricies augue, a efficitur urna. Praesent in nisi vehicula, pulvinar lorem ut, convallis odio.',
    dateCreated: new Date('2024-05-14')
  },
  {
    id: 'gQkFNG',
    title: 'Validate bug fixes from last sprint',
    summary: 'Vivamus lobortis id quam vitae molestie. Proin molestie porttitor ultricies. ',
    dateCreated: new Date('2024-05-22')
  }
];

export const bugs: WorkItem[] = [
  {
    id: 'HE2BkE',
    title: 'Fix header layout on mobile.',
    summary: 'Duis gravida dolor vitae magna finibus, non dictum ipsum rutrum. Sed eu neque scelerisque, accumsan felis in, auctor tortor. ',
    dateCreated: new Date('2024-05-29')
  },
  {
    id: 'qNdzn3',
    title: 'Internal server error after confirming email',
    summary: 'Nulla rhoncus ligula sit amet tortor laoreet suscipit. Morbi consequat porta diam vel fermentum. In malesuada,',
    dateCreated: new Date('2024-05-28')
  },
  {
    id: 'CZ0OG3',
    title: 'Unable to update profile picture',
    summary: 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse feugiat venenatis diam.',
    dateCreated: new Date('2024-05-31')
  },
  {
    id: 'bg862c',
    title: 'Sticky footer dissapearing on some screens ',
    summary: 'Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.',
    dateCreated: new Date('2024-06-01')
  }
];

export const userStories: WorkItem[] = [
  {
    id: 'c9V5Gv',
    title: 'Allow login with Google',
    summary: 'Nam ut mi interdum, eleifend nisl at, pellentesque metus. Donec rhoncus urna libero, eu bibendum ex tincidunt vel. ',
    dateCreated: new Date('2024-07-28')
  },
  {
    id: 'wEHvqz',
    title: 'Add full text search feature',
    summary: 'Nullam tempor orci leo, id aliquet lacus varius eu. Maecenas rutrum erat id metus malesuada.',
    dateCreated: new Date('2024-05-16')
  },
  {
    id: '7iWH0b',
    title: 'Allow side by side product comparison',
    summary: 'Nulla posuere libero non placerat gravida. Proin vehicula laoreet volutpat. ',
    dateCreated: new Date('2024-05-29')
  }
];
